// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:LetPortal.Tests.UTs.Portal.Services.FileServiceTests.FileOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Filled_Params_And_Search_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Filled_Params_And_Search_Test")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Filled_Params_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Filled_Params_Test")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Nothing_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Executions.DynamicQueryBuilderTests.Generate_Postgre_Query_With_Nothing_Test")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_In_Mongo_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_In_Mongo_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_In_Mongo_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_Not_Supported_DbType_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Execute_Dynamic_Command_Not_Supported_DbType_Test' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_Not_Supported_DbType_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_Not_Supported_DbType_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Execute_Dynamic_Command_Not_Supported_DbType_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Extract_Columns_In_Mongo_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Extract_Columns_In_Mongo_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.DatabaseServiceTests.Extract_Columns_In_Mongo_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.FileServiceTests.Upload_File_Test~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name LetPortal.Tests.UTs.Portal.Services.FileServiceTests.Upload_File_Test().", Justification = "<Pending>", Scope = "member", Target = "~M:LetPortal.Tests.UTs.Portal.Services.FileServiceTests.Upload_File_Test~System.Threading.Tasks.Task")]