name: LET Portal Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build with dotnet
      run: dotnet build
      working-directory: ./src/web-apis
    - name: Install npm packages
      run: npm install
      working-directory: ./src/web-portal
    - name: Build npm packages
      run: npm run debug
      working-directory: ./src/web-portal
    
