using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using LetPortal.CMS.Features.Blogs.Entities;
using LetPortal.Core.Utils;
using LetPortal.Core.Versions;

namespace PersonalBlog.Tools.BlogPosts
{
    public class BlogPost_0_0_1 : IPersonalBlogVersion
    {
        public string VersionNumber => "1.0.0";

        public Task Downgrade(IVersionContext versionContext)
        {
            versionContext.DeleteData<Post>("5f0ab7065063a011e8fc2f88");
            return Task.CompletedTask;
        }

        public Task Upgrade(IVersionContext versionContext)
        {
            for (var i = 0; i < 100; i++)
            {
                var post = new Post
                {
                    Id = DataUtil.GenerateUniqueId(),
                    BlogId = "5f0ab7065063a011e8fc2f8d",
                    CreatedDate = DateTime.UtcNow,
                    AllowUserComment = true,
                    Author = "admin",
                    Content = "Simple Blog",
                    Title = "This is simeple blog " + i.ToString(),
                    Description = "Simple blog is generated by LetPortal  " + i.ToString(),
                    ReadDuration = 5,
                    ShowComment = true,
                    UrlPath = "dot-net-simple-blog-" + i.ToString(),
                    Tags = i % 2 == 0 ? new List<string> { "5f1abacf7a4ae23814977402" } : new List<string> { "5f1ef6fce9ce36726865ebc6" }
                };

                versionContext.InsertData(post);
            }

            for (var i = 0; i < 100; i++)
            {
                var post = new Post
                {
                    Id = DataUtil.GenerateUniqueId(),
                    BlogId = "5fb398bd8dbe2c62e0a674ce",
                    CreatedDate = DateTime.UtcNow,
                    AllowUserComment = true,
                    Author = "admin",
                    Content = "Simple Blog",
                    Title = "This is simeple blog " + i.ToString(),
                    Description = "Simple blog is generated by LetPortal  " + i.ToString(),
                    ReadDuration = 5,
                    ShowComment = true,
                    UrlPath = "angular-simple-blog-" + i.ToString(),
                    Tags = i % 2 == 0 ? new List<string> { "5f1abacf7a4ae23814977402" } : new List<string> { "5f1ef6fce9ce36726865ebc6" }
                };

                versionContext.InsertData(post);
            }

            return Task.CompletedTask;

        }
    }
}
